version: '3.8'
services:
  app:
    build: .
    container_name: ytmoodapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
  redis:
    image: redis:7
    container_name: ytmoodapi_redis
    ports:
      - "6379:6379"
  db:
    image: postgres:14
    container_name: ytmoodapi_db
    environment:
      POSTGRES_USER: ytmood
      POSTGRES_PASSWORD: ytmoodpw
      POSTGRES_DB: ytmood
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 